import type { Incident } from "./incident-types";

export const initialIncidents: Incident[] = [
  // ── EN EVALUACION — informe enviado al Comité ────────────────────────────────
  {
    id: "GRD-2026-0008",
    name: "Deslizamiento en Zona de Ladera — Independencia",
    responsible: "Carlos Méndez",
    category: "Deslizamientos",
    fuenteAlerta: ["Defensa Civil"],
    location: "Independencia",
    status: "EN EVALUACION",
    startDate: "2026-04-20",
    endDate: "2026-04-20",
    participants: 18,
    description:
      "Deslizamiento de tierra afectó cuatro viviendas en ladera pronunciada. Dos familias quedaron sin acceso a sus hogares.",
    causaSuceso:
      "Saturación del suelo por lluvias acumuladas durante la semana. El terreno arcilloso sin vegetación cedió ante la presión hídrica.",
    pais: "Perú",
    region: "Lima Metropolitana",
    distrito: "Independencia",
    parroquia: "Parroquia Cristo Salvador",
    direccion: "AA.HH. El Ermitaño, Zona C, Mz. K Lt. 3",
    referencia: "Subiendo por la escalera de cemento hasta el nivel 4 del asentamiento",
    nivelAfectacion: "Severo",
    numFamiliasAfectadas: 4,
    gruposVulnerables: ["Adultos mayores (60+)", "Personas con discapacidad"],
    necesidadesUrgentes: ["Refugio temporal", "Alimentación", "Agua potable"],
    affectedPeople: [
      {
        id: "p1",
        tipoDoc: "DNI",
        dni: "40123456",
        nombre: "Elvira",
        apellidoPaterno: "Mamani",
        apellidoMaterno: "Quispe",
        edad: "68",
        genero: "Femenino",
        celular: "976543210",
        parentesco: "Jefa de hogar",
        familiaId: "fam-mamani-8",
        familiaNombre: "Familia Mamani Quispe",
      },
      {
        id: "p2",
        tipoDoc: "DNI",
        dni: "40123457",
        nombre: "Rubén",
        apellidoPaterno: "Mamani",
        apellidoMaterno: "Condori",
        edad: "71",
        genero: "Masculino",
        celular: "976543211",
        parentesco: "Cónyuge",
        familiaId: "fam-mamani-8",
        familiaNombre: "Familia Mamani Quispe",
      },
    ],
    uploadedFiles: [
      "foto_deslizamiento_1.jpg",
      "foto_viviendas_afectadas.jpg",
      "acta_campo_ind.pdf",
    ],
    createdBy: "especialistaGRD",
    createdAt: "2026-04-20T09:00:00.000Z",
    updatedAt: "2026-04-22T11:30:00.000Z",
    updatedBy: "especialistaGRD",
    reportadoPor: {
      nombreCompleto: "Elvira Mamani Quispe",
      dni: "40123456",
      telefono: "976 543 210",
    },
    brigadistaAsignado: {
      id: "B-001",
      nombre: "Ana Torres",
      parroquia: "Parroquia San Juan Bautista",
      celular: "987-654-321",
      fechaAsignacion: "2026-04-20T11:00:00.000Z",
      asignadoPor: "especialistaGRD",
    },
    infoPrimeraVisita: {
      fechaVisita: "2026-04-21",
      responsable: "Ana Torres",
      motivoVisita: "Levantamiento de información por deslizamiento de ladera",
      objetivos: "Empadronar familias afectadas y evaluar condiciones de habitabilidad",
      descripcionEvento:
        "Cuatro viviendas afectadas en ladera pronunciada. Dos viviendas con daño estructural severo e inhabitable. Dos viviendas con daño parcial. Acceso bloqueado por material deslizado.",
      condHabitabilidad: {
        agua: false,
        electricidad: false,
        refugio: false,
        saludAmbiental: false,
        acceso: false,
      },
      nivelVulnerabilidad: "Crítico",
      necesidadesPrioritarias: ["Refugio temporal urgente", "Alimentación", "Agua potable"],
      recomendacion: "Las dos familias más afectadas requieren albergue inmediato.",
      observaciones: "Adultos mayores de 68 y 71 años sin familiares en Lima. Alta vulnerabilidad.",
    },
    informeEvaluacion: {
      fecha: "2026-04-22",
      elaboradoPor: "especialistaGRD",
      emitidoPor: "Carlos Méndez — Especialista GRD",
      dirigidoA: ["Comité de donaciones"],
      oficina: "Oficina de Gestión Pastoral / GRD",
      motivo:
        "Deslizamiento de ladera con daño habitacional severo en dos viviendas y adultos mayores sin red de apoyo familiar.",
      objetivoGeneral: "Brindar asistencia humanitaria de emergencia a la Familia Mamani Quispe.",
      objetivosEspecificos: [
        "Proveer alimentos básicos para 14 días ante el bloqueo de acceso.",
        "Suministrar artículos de higiene esencial para los adultos mayores.",
        "Gestionar coordinación con Defensa Civil para evaluación estructural.",
      ],
      analisisSituacion:
        "Cuatro familias con daño habitacional severo. Dos viviendas declaradas inhabitables por Defensa Civil. Los adultos mayores (68 y 71 años) sin red de apoyo familiar en Lima.",
      hallazgosBullets: [
        "Vivienda sin acceso a agua potable ni electricidad.",
        "Adultos mayores de 68 y 71 años sin familiares en Lima.",
        "Defensa Civil declaró la zona en riesgo alto.",
        "El material deslizado bloqueó el único acceso peatonal.",
      ],
      nivelUrgencia: "Inmediata",
      tipoIntervencion: "Donación en especie",
      descripcionAyuda:
        "Kit de refugio temporal (carpas) para 2 familias + kit de alimentos básicos (14 días) para 4 familias + bidones de agua potable. Total estimado: S/ 2,400.",
      criteriosPriorizacion: [
        "Pérdida total o parcial de vivienda",
        "Adultos mayores",
        "Sin redes de apoyo familiar",
        "Vulnerabilidad crítica",
      ],
      recomendacionComite:
        "Se recomienda aprobación inmediata. Las familias llevan 2 noches sin refugio adecuado.",
      conclusiones:
        "La Familia Mamani Quispe se encuentra en situación de alta vulnerabilidad. La intervención con kit de víveres e higiene es necesaria e inmediata.",
      asignacionPorFamilia: [
        {
          familiaId: "fam-mamani-8",
          familiaNombre: "Familia Mamani Quispe",
          observacionesEspecialista: "Adultos mayores sin red de apoyo. Prioridad máxima.",
          kits: [
            {
              id: "k-vv-8-1",
              nombre: "Kit de Víveres",
              items: [
                { codigo: "VV-001", descripcion: "Arroz 5kg", cantidad: 2 },
                { codigo: "VV-002", descripcion: "Aceite 1L", cantidad: 2 },
                { codigo: "VV-003", descripcion: "Atún en lata", cantidad: 4 },
                {
                  codigo: "VV-004",
                  descripcion: "Leche evaporada",
                  cantidad: 4,
                },
                { codigo: "VV-005", descripcion: "Fideos 500g", cantidad: 2 },
                { codigo: "VV-006", descripcion: "Azúcar 1kg", cantidad: 1 },
                {
                  codigo: "VV-007",
                  descripcion: "Conservas mixtas",
                  cantidad: 3,
                },
              ],
            },
            {
              id: "k-hg-8-1",
              nombre: "Kit de Higiene",
              items: [
                {
                  codigo: "HG-001",
                  descripcion: "Jabón de tocador x3",
                  cantidad: 2,
                },
                {
                  codigo: "HG-002",
                  descripcion: "Papel higiénico x4",
                  cantidad: 2,
                },
                {
                  codigo: "HG-003",
                  descripcion: "Pasta dental + cepillo",
                  cantidad: 2,
                },
                {
                  codigo: "HG-004",
                  descripcion: "Toallas desechables",
                  cantidad: 1,
                },
              ],
            },
          ],
        },
      ],
    },
    history: [
      {
        id: "h1",
        user: "especialistaGRD",
        userRole: "especialistaGRD",
        timestamp: "2026-04-20T09:00:00.000Z",
        action: "creación",
        newStatus: "ABIERTO",
        notes: "Registro — deslizamiento reportado por Defensa Civil",
      },
      {
        id: "h2",
        user: "especialistaGRD",
        userRole: "especialistaGRD",
        timestamp: "2026-04-20T11:00:00.000Z",
        action: "asignación",
        prevStatus: "ABIERTO",
        newStatus: "ASIGNADO",
        notes: "Brigadista asignado: Ana Torres.",
      },
      {
        id: "h3",
        user: "brigadista",
        userRole: "brigadista",
        timestamp: "2026-04-21T15:00:00.000Z",
        action: "campo",
        prevStatus: "ASIGNADO",
        newStatus: "DATA RECOPILADA",
        notes: "Levantamiento completado. 2 personas empadronadas. 3 evidencias adjuntas.",
      },
      {
        id: "h4",
        user: "especialistaGRD",
        userRole: "especialistaGRD",
        timestamp: "2026-04-22T11:30:00.000Z",
        action: "informe_evaluacion",
        prevStatus: "DATA RECOPILADA",
        newStatus: "EN EVALUACION",
        notes:
          "Informe de evaluación social elaborado. Tipo: Donación en especie. Urgencia: Inmediata. Enviado al Comité.",
      },
    ],
  },

  // ── OBSERVADO — Comité devolvió con observaciones ────────────────────────────
  {
    id: "GRD-2026-0010",
    name: "Inundación Viviendas — Lurigancho-Chosica",
    responsible: "Carlos Méndez",
    category: "Inundaciones",
    fuenteAlerta: ["Municipalidad"],
    location: "Lurigancho-Chosica",
    status: "OBSERVADO",
    startDate: "2026-04-22",
    endDate: "2026-04-22",
    participants: 20,
    description:
      "Inundación de viviendas en zona baja del distrito por crecida del río Rímac. Cinco familias requieren evaluación.",
    causaSuceso:
      "Crecida del río Rímac por lluvias en la sierra. El sistema de drenaje del AA.HH. colapsó.",
    pais: "Perú",
    region: "Lima Metropolitana",
    distrito: "Lurigancho",
    parroquia: "Parroquia Sagrado Corazón de Jesús",
    direccion: "AA.HH. Los Claveles, Mz. H Lt. 2, Zona Baja",
    nivelAfectacion: "Moderado",
    numFamiliasAfectadas: 5,
    gruposVulnerables: ["Niños (0–12 años)", "Adultos mayores (60+)"],
    necesidadesUrgentes: ["Agua potable", "Alimentación", "Higiene personal"],
    affectedPeople: [],
    uploadedFiles: ["foto_inundacion_chosica.jpg", "acta_campo_lurigancho.pdf"],
    createdBy: "especialistaGRD",
    createdAt: "2026-04-22T08:00:00.000Z",
    updatedAt: "2026-04-26T09:00:00.000Z",
    updatedBy: "comite",
    reportadoPor: {
      nombreCompleto: "Pedro Pablo Quispe Ccallo",
      dni: "28901234",
      telefono: "943 216 789",
    },
    brigadistaAsignado: {
      id: "B-005",
      nombre: "Jorge Luis Vargas Díaz",
      parroquia: "Parroquia San José Obrero",
      celular: "998-123-456",
      fechaAsignacion: "2026-04-22T10:00:00.000Z",
      asignadoPor: "especialistaGRD",
    },
    infoPrimeraVisita: {
      fechaVisita: "2026-04-23",
      responsable: "Jorge Luis Vargas Díaz",
      motivoVisita: "Levantamiento de información por inundación",
      objetivos: "Empadronar familias y evaluar condiciones de habitabilidad",
      descripcionEvento:
        "Cinco viviendas con hasta 40cm de agua interior. Pisos y paredes afectadas. Pérdida de enseres.",
      condHabitabilidad: {
        agua: false,
        electricidad: false,
        refugio: true,
        saludAmbiental: false,
        acceso: true,
      },
      nivelVulnerabilidad: "Medio",
      necesidadesPrioritarias: ["Agua potable", "Alimentación", "Kits de higiene"],
      recomendacion: "Entrega de kits de higiene y alimentos básicos para 5 familias.",
    },
    informeEvaluacion: {
      fecha: "2026-04-24",
      elaboradoPor: "especialistaGRD",
      emitidoPor: "Carlos Méndez — Especialista GRD",
      dirigidoA: ["Comité de donaciones"],
      oficina: "Oficina de Gestión Pastoral / GRD",
      motivo: "Inundación de viviendas por crecida del río Rímac con cinco familias afectadas.",
      objetivoGeneral:
        "Atender las necesidades básicas de higiene y alimentación de las cinco familias afectadas.",
      analisisSituacion:
        "Cinco familias con habitabilidad comprometida temporalmente. Los daños son de tipo moderado.",
      hallazgosBullets: [
        "Cinco viviendas con hasta 40 cm de agua interior.",
        "Pérdida de enseres, ropa y alimentos almacenados.",
        "Sin acceso a agua potable ni electricidad.",
        "Presencia de niños y adultos mayores en al menos 3 familias.",
      ],
      nivelUrgencia: "Media",
      tipoIntervencion: "Donación en especie",
      descripcionAyuda:
        "Kits de higiene (5 kits) + canastas de alimentos básicos (5 canastas, 7 días).",
      criteriosPriorizacion: ["Niños o adolescentes en el hogar", "Adultos mayores"],
      recomendacionComite:
        "Se recomienda aprobar la donación de kits de higiene y alimentos básicos para las 5 familias.",
      observacionesComite:
        "El Comité solicita actualizar el informe con el número exacto de personas afectadas por familia y adjuntar evidencia fotográfica de cada vivienda afectada. Además, clarificar si alguna familia ya recibió apoyo de la municipalidad.",
      conclusiones:
        "Las cinco familias requieren apoyo en higiene y alimentación. Pendiente empadronamiento individual por familia.",
    },
    history: [
      {
        id: "h1",
        user: "especialistaGRD",
        userRole: "especialistaGRD",
        timestamp: "2026-04-22T08:00:00.000Z",
        action: "creación",
        newStatus: "ABIERTO",
        notes: "Registro — alerta municipal por inundación",
      },
      {
        id: "h2",
        user: "especialistaGRD",
        userRole: "especialistaGRD",
        timestamp: "2026-04-22T10:00:00.000Z",
        action: "asignación",
        prevStatus: "ABIERTO",
        newStatus: "ASIGNADO",
        notes: "Brigadista asignado: Jorge Luis Vargas Díaz.",
      },
      {
        id: "h3",
        user: "brigadista",
        userRole: "brigadista",
        timestamp: "2026-04-23T14:00:00.000Z",
        action: "campo",
        prevStatus: "ASIGNADO",
        newStatus: "DATA RECOPILADA",
        notes: "Levantamiento completado.",
      },
      {
        id: "h4",
        user: "especialistaGRD",
        userRole: "especialistaGRD",
        timestamp: "2026-04-24T11:00:00.000Z",
        action: "informe_evaluacion",
        prevStatus: "DATA RECOPILADA",
        newStatus: "EN EVALUACION",
        notes: "Informe elaborado y enviado al Comité.",
      },
      {
        id: "h5",
        user: "comite",
        userRole: "comite",
        timestamp: "2026-04-26T09:00:00.000Z",
        action: "observacion",
        prevStatus: "EN EVALUACION",
        newStatus: "OBSERVADO",
        notes:
          "Se devuelve el informe con observaciones: falta número de personas por familia y evidencia fotográfica por vivienda.",
      },
    ],
  },

  // ── APROBADO — Comité aprobó, pendiente atención ─────────────────────────────
  {
    id: "GRD-2026-0009",
    name: "Vendaval con Pérdida de Techo — El Agustino",
    responsible: "Carlos Méndez",
    category: "Pérdida parcial de la vivienda",
    fuenteAlerta: ["Brigadista parroquial"],
    location: "El Agustino",
    status: "APROBADO",
    startDate: "2026-04-15",
    endDate: "2026-04-15",
    participants: 7,
    description:
      "Fuertes vientos arrancaron el techo de calamina de una vivienda dejando a la familia expuesta.",
    causaSuceso:
      "Vendaval de aproximadamente 60 km/h arrancó el sistema de techos de calamina mal asegurados.",
    pais: "Perú",
    region: "Lima Metropolitana",
    distrito: "El Agustino",
    parroquia: "Parroquia San Cayetano",
    direccion: "Jr. Huánuco 891, AA.HH. La Corporación, Mz. C Lt. 7",
    nivelAfectacion: "Moderado",
    numFamiliasAfectadas: 2,
    gruposVulnerables: ["Niños (0–12 años)", "Gestantes / Madres lactantes"],
    necesidadesUrgentes: ["Materiales de construcción", "Abrigo / Ropa", "Alimentación"],
    affectedPeople: [
      {
        id: "p1",
        tipoDoc: "DNI",
        dni: "55678901",
        nombre: "Sofía",
        apellidoPaterno: "Guerrero",
        apellidoMaterno: "Ríos",
        edad: "28",
        genero: "Femenino",
        celular: "985432167",
        parentesco: "Jefa de hogar",
        familiaId: "fam-guerrero-9",
        familiaNombre: "Familia Guerrero Ríos",
        situacionActual: "Gestante",
      },
      {
        id: "p2",
        tipoDoc: "DNI",
        dni: "55678902",
        nombre: "Sebastián",
        apellidoPaterno: "Guerrero",
        apellidoMaterno: "Ríos",
        edad: "3",
        genero: "Masculino",
        celular: "",
        parentesco: "Hijo",
        familiaId: "fam-guerrero-9",
        familiaNombre: "Familia Guerrero Ríos",
      },
    ],
    uploadedFiles: ["foto_techo_vendaval.jpg", "acta_campo_agustino.pdf"],
    createdBy: "brigadista",
    createdAt: "2026-04-15T10:00:00.000Z",
    updatedAt: "2026-04-18T16:00:00.000Z",
    updatedBy: "comite",
    reportadoPor: {
      nombreCompleto: "Sofía Guerrero Ríos",
      dni: "55678901",
      telefono: "985 432 167",
    },
    brigadistaAsignado: {
      id: "B-005",
      nombre: "Jorge Luis Vargas Díaz",
      parroquia: "Parroquia San José Obrero",
      celular: "998-123-456",
      fechaAsignacion: "2026-04-15T12:00:00.000Z",
      asignadoPor: "especialistaGRD",
    },
    informeEvaluacion: {
      fecha: "2026-04-17",
      elaboradoPor: "especialistaGRD",
      analisisSituacion:
        "Dos familias con pérdida de techo. Una madre gestante de 7 meses expuesta a condiciones de humedad y frío.",
      nivelUrgencia: "Alta",
      tipoIntervencion: "Donación en especie",
      descripcionAyuda:
        "Kit de materiales: 8 calaminas + listones para 2 familias + kit de abrigo para madre gestante.",
      criteriosPriorizacion: [
        "Gestantes o madres lactantes",
        "Niños o adolescentes en el hogar",
        "Pérdida total o parcial de vivienda",
      ],
      recomendacionComite:
        "Se recomienda aprobar. La presencia de una gestante de 7 meses sin techo representa un riesgo sanitario claro.",
    },
    history: [
      {
        id: "h1",
        user: "brigadista",
        userRole: "brigadista",
        timestamp: "2026-04-15T10:00:00.000Z",
        action: "creación",
        newStatus: "ABIERTO",
        notes: "Registro inicial — vendaval reportado por brigadista parroquial",
      },
      {
        id: "h2",
        user: "especialistaGRD",
        userRole: "especialistaGRD",
        timestamp: "2026-04-15T12:00:00.000Z",
        action: "asignación",
        prevStatus: "ABIERTO",
        newStatus: "ASIGNADO",
        notes: "Brigadista asignado: Jorge Luis Vargas Díaz.",
      },
      {
        id: "h3",
        user: "brigadista",
        userRole: "brigadista",
        timestamp: "2026-04-16T14:00:00.000Z",
        action: "campo",
        prevStatus: "ASIGNADO",
        newStatus: "DATA RECOPILADA",
        notes: "Levantamiento completado. 2 familias empadronadas.",
      },
      {
        id: "h4",
        user: "especialistaGRD",
        userRole: "especialistaGRD",
        timestamp: "2026-04-17T10:00:00.000Z",
        action: "informe_evaluacion",
        prevStatus: "DATA RECOPILADA",
        newStatus: "EN EVALUACION",
        notes: "Informe elaborado. Donación en especie recomendada. Enviado al Comité.",
      },
      {
        id: "h5",
        user: "comite",
        userRole: "comite",
        timestamp: "2026-04-18T16:00:00.000Z",
        action: "aprobacion",
        prevStatus: "EN EVALUACION",
        newStatus: "APROBADO",
        notes: "Donación aprobada. Kit de materiales y abrigo aprobado para entrega.",
      },
    ],
  },

  // ── ATENDIDO — donación entregada, pendiente seguimiento ─────────────────────
  {
    id: "GRD-2026-0004",
    name: "Colapso Estructural en Mercado Municipal",
    responsible: "Carlos Méndez",
    category: "Colapso de infraestructura",
    fuenteAlerta: ["Defensa Civil"],
    location: "Ate",
    status: "ATENDIDO",
    startDate: "2026-03-28",
    endDate: "2026-03-28",
    participants: 48,
    description:
      "Colapso parcial del techo de mercado municipal. Doce familias de comerciantes requieren apoyo de emergencia.",
    causaSuceso:
      "Sobrecarga por materiales acumulados sobre el techo y deterioro estructural no atendido.",
    pais: "Perú",
    region: "Lima Metropolitana",
    distrito: "Ate",
    parroquia: "Parroquia Santa Rosa",
    direccion: "Mercado Municipal de Vitarte, Av. Separadora Industrial 2568",
    nivelAfectacion: "Severo",
    numFamiliasAfectadas: 12,
    gruposVulnerables: ["Adultos mayores (60+)"],
    necesidadesUrgentes: ["Apoyo económico", "Alimentación"],
    affectedPeople: [],
    uploadedFiles: ["informe_colapso_mercado.pdf", "acta_donacion_ate.pdf"],
    createdBy: "brigadista",
    createdAt: "2026-03-28T07:00:00.000Z",
    updatedAt: "2026-04-04T10:00:00.000Z",
    updatedBy: "especialistaGRD",
    reportadoPor: {
      nombreCompleto: "Rosa Amelia Ccoa Mamani",
      dni: "32456789",
      telefono: "964 321 789",
    },
    informeEvaluacion: {
      fecha: "2026-03-31",
      elaboradoPor: "especialistaGRD",
      analisisSituacion:
        "Las 12 familias de comerciantes perdieron sus fuentes de ingreso. La estructura ha sido declarada insegura.",
      nivelUrgencia: "Alta",
      tipoIntervencion: "Donación económica",
      descripcionAyuda:
        "Kit de apoyo económico de emergencia (S/ 300 por familia × 12 familias = S/ 3,600 total).",
      criteriosPriorizacion: [
        "Pérdida de fuente de ingresos",
        "Sin redes de apoyo familiar",
        "Adultos mayores",
        "Situación de pobreza extrema",
      ],
      recomendacionComite: "Se recomienda aprobar la donación económica.",
    },
    informeAtencion: {
      fecha: "2026-04-04",
      elaboradoPor: "especialistaGRD",
      descripcionEntrega:
        "Entrega del apoyo económico de emergencia a los 12 comerciantes afectados en el local de la Parroquia Santa Rosa.",
      itemsEntregados: [
        "S/ 300 en efectivo por familia (12 familias)",
        "Kit de canasta alimentaria básica",
      ],
      montoTotal: 3600,
      beneficiariosAtendidos: 12,
    },
    history: [
      {
        id: "h1",
        user: "brigadista",
        userRole: "brigadista",
        timestamp: "2026-03-28T07:00:00.000Z",
        action: "creación",
        newStatus: "ABIERTO",
        notes: "Registro — colapso reportado por Defensa Civil",
      },
      {
        id: "h2",
        user: "especialistaGRD",
        userRole: "especialistaGRD",
        timestamp: "2026-03-29T09:00:00.000Z",
        action: "asignación",
        prevStatus: "ABIERTO",
        newStatus: "ASIGNADO",
        notes: "Brigadista asignado.",
      },
      {
        id: "h3",
        user: "brigadista",
        userRole: "brigadista",
        timestamp: "2026-03-30T15:00:00.000Z",
        action: "campo",
        prevStatus: "ASIGNADO",
        newStatus: "DATA RECOPILADA",
        notes: "Levantamiento completado.",
      },
      {
        id: "h4",
        user: "especialistaGRD",
        userRole: "especialistaGRD",
        timestamp: "2026-03-31T11:00:00.000Z",
        action: "informe_evaluacion",
        prevStatus: "DATA RECOPILADA",
        newStatus: "EN EVALUACION",
        notes: "Informe elaborado. Donación económica recomendada.",
      },
      {
        id: "h5",
        user: "comite",
        userRole: "comite",
        timestamp: "2026-04-02T16:00:00.000Z",
        action: "aprobacion",
        prevStatus: "EN EVALUACION",
        newStatus: "APROBADO",
        notes: "Donación aprobada. S/ 3,600 para 12 familias.",
      },
      {
        id: "h6",
        user: "especialistaGRD",
        userRole: "especialistaGRD",
        timestamp: "2026-04-04T10:00:00.000Z",
        action: "atencion",
        prevStatus: "APROBADO",
        newStatus: "ATENDIDO",
        notes: "Donación entregada. 12 familias atendidas en Parroquia Santa Rosa.",
      },
    ],
  },

  // ── SEGUIMIENTO ABIERTO — seguimiento activo ─────────────────────────────────
  {
    id: "GRD-2026-0006",
    name: "Incendio Forestal Urbano — Villa El Salvador",
    responsible: "Carlos Méndez",
    category: "Incendios",
    fuenteAlerta: ["Brigadista parroquial"],
    location: "Villa El Salvador",
    status: "SEGUIMIENTO ABIERTO",
    startDate: "2026-04-14",
    endDate: "2026-04-14",
    participants: 3,
    description:
      "Incendio en área de vegetación seca cercana a viviendas. Una familia con daños menores en fachada.",
    pais: "Perú",
    region: "Lima Metropolitana",
    distrito: "Villa El Salvador",
    nivelAfectacion: "Leve",
    numFamiliasAfectadas: 1,
    affectedPeople: [
      {
        id: "p1",
        tipoDoc: "DNI",
        dni: "61234567",
        nombre: "Norma",
        apellidoPaterno: "Flores",
        apellidoMaterno: "Zapata",
        edad: "35",
        genero: "Femenino",
        celular: "976543219",
        parentesco: "Jefa de hogar",
      },
    ],
    uploadedFiles: ["reporte_incendio_forestal.pdf", "acta_donacion_ves.pdf"],
    createdBy: "brigadista",
    createdAt: "2026-04-14T13:00:00.000Z",
    updatedAt: "2026-04-22T10:00:00.000Z",
    updatedBy: "especialistaGRD",
    informeEvaluacion: {
      fecha: "2026-04-17",
      elaboradoPor: "especialistaGRD",
      analisisSituacion:
        "Afectación leve: daños menores en fachada y un miembro con síntomas respiratorios por inhalación.",
      nivelUrgencia: "Media",
      tipoIntervencion: "Donación en especie",
      descripcionAyuda: "Kit de higiene completo (1 kit) + coordinación con Centro de Salud.",
      criteriosPriorizacion: ["Niños o adolescentes en el hogar"],
      recomendacionComite:
        "Aprobar donación del kit de higiene. Costo mínimo e impacto significativo.",
    },
    informeAtencion: {
      fecha: "2026-04-20",
      elaboradoPor: "especialistaGRD",
      descripcionEntrega:
        "Entrega de kit de higiene en domicilio. La señora Norma Flores Zapata firmó el acta.",
      itemsEntregados: ["Kit de higiene completo"],
      beneficiariosAtendidos: 1,
    },
    history: [
      {
        id: "h1",
        user: "brigadista",
        userRole: "brigadista",
        timestamp: "2026-04-14T13:00:00.000Z",
        action: "creación",
        newStatus: "ABIERTO",
        notes: "Registro — incendio forestal",
      },
      {
        id: "h2",
        user: "especialistaGRD",
        userRole: "especialistaGRD",
        timestamp: "2026-04-15T08:00:00.000Z",
        action: "asignación",
        prevStatus: "ABIERTO",
        newStatus: "ASIGNADO",
        notes: "Brigadista asignado.",
      },
      {
        id: "h3",
        user: "brigadista",
        userRole: "brigadista",
        timestamp: "2026-04-16T11:00:00.000Z",
        action: "campo",
        prevStatus: "ASIGNADO",
        newStatus: "DATA RECOPILADA",
        notes: "Levantamiento completado.",
      },
      {
        id: "h4",
        user: "especialistaGRD",
        userRole: "especialistaGRD",
        timestamp: "2026-04-17T10:00:00.000Z",
        action: "informe_evaluacion",
        prevStatus: "DATA RECOPILADA",
        newStatus: "EN EVALUACION",
        notes: "Informe elaborado.",
      },
      {
        id: "h5",
        user: "comite",
        userRole: "comite",
        timestamp: "2026-04-19T09:00:00.000Z",
        action: "aprobacion",
        prevStatus: "EN EVALUACION",
        newStatus: "APROBADO",
        notes: "Kit de higiene aprobado.",
      },
      {
        id: "h6",
        user: "especialistaGRD",
        userRole: "especialistaGRD",
        timestamp: "2026-04-20T10:00:00.000Z",
        action: "atencion",
        prevStatus: "APROBADO",
        newStatus: "ATENDIDO",
        notes: "Kit entregado.",
      },
      {
        id: "h7",
        user: "especialistaGRD",
        userRole: "especialistaGRD",
        timestamp: "2026-04-22T10:00:00.000Z",
        action: "seguimiento",
        prevStatus: "ATENDIDO",
        newStatus: "SEGUIMIENTO ABIERTO",
        notes: "Primer seguimiento — situación mejora.",
      },
    ],
  },

  // ── RECHAZADO — donación rechazada por el Comité ─────────────────────────────
  {
    id: "GRD-2026-0005",
    name: "Pérdida Parcial de Techo por Vendaval — Comas",
    responsible: "Carlos Méndez",
    category: "Pérdida parcial de la vivienda",
    fuenteAlerta: ["Brigadista parroquial"],
    location: "Comas",
    status: "RECHAZADO",
    startDate: "2026-04-12",
    endDate: "2026-04-12",
    participants: 4,
    description:
      "Fuertes vientos desplazaron calaminas de techo de dos viviendas. Los daños son menores y reparables.",
    pais: "Perú",
    region: "Lima Metropolitana",
    distrito: "Comas",
    nivelAfectacion: "Leve",
    numFamiliasAfectadas: 2,
    affectedPeople: [],
    uploadedFiles: ["informe_vendaval_comas.pdf"],
    createdBy: "brigadista",
    createdAt: "2026-04-12T11:00:00.000Z",
    updatedAt: "2026-04-15T09:00:00.000Z",
    updatedBy: "comite",
    reportadoPor: {
      nombreCompleto: "Alicia Vargas Moreno",
      dni: "49876543",
      telefono: "964 123 456",
    },
    informeEvaluacion: {
      fecha: "2026-04-15",
      elaboradoPor: "especialistaGRD",
      analisisSituacion:
        "Daños leves: solo calaminas de techo desplazadas. Las familias mantienen habitabilidad básica.",
      nivelUrgencia: "Baja",
      tipoIntervencion: "No aplica",
      descripcionAyuda:
        "No se recomienda donación. Las familias pueden gestionar la reparación de forma autónoma.",
      criteriosPriorizacion: [],
      recomendacionComite:
        "El caso no cumple criterios de priorización. Daños leves y subsanables con recursos propios.",
    },
    history: [
      {
        id: "h1",
        user: "brigadista",
        userRole: "brigadista",
        timestamp: "2026-04-12T11:00:00.000Z",
        action: "creación",
        newStatus: "ABIERTO",
        notes: "Registro — vendaval",
      },
      {
        id: "h2",
        user: "especialistaGRD",
        userRole: "especialistaGRD",
        timestamp: "2026-04-13T09:00:00.000Z",
        action: "asignación",
        prevStatus: "ABIERTO",
        newStatus: "ASIGNADO",
        notes: "Brigadista asignado.",
      },
      {
        id: "h3",
        user: "brigadista",
        userRole: "brigadista",
        timestamp: "2026-04-14T14:00:00.000Z",
        action: "campo",
        prevStatus: "ASIGNADO",
        newStatus: "DATA RECOPILADA",
        notes: "Levantamiento completado — daños menores.",
      },
      {
        id: "h4",
        user: "especialistaGRD",
        userRole: "especialistaGRD",
        timestamp: "2026-04-15T08:00:00.000Z",
        action: "informe_evaluacion",
        prevStatus: "DATA RECOPILADA",
        newStatus: "EN EVALUACION",
        notes: "Informe elaborado. No aplica intervención.",
      },
      {
        id: "h5",
        user: "comite",
        userRole: "comite",
        timestamp: "2026-04-15T09:00:00.000Z",
        action: "rechazo",
        prevStatus: "EN EVALUACION",
        newStatus: "RECHAZADO",
        notes: "No cumple criterios de priorización. Caso cerrado.",
      },
    ],
  },

  // ── CERRADO — caso completamente cerrado ─────────────────────────────────────
  {
    id: "GRD-2026-0011",
    name: "Sismo Leve con Grietas en Vivienda",
    responsible: "Carlos Méndez",
    category: "Sismos",
    fuenteAlerta: ["Comunidad / Vecinos"],
    location: "Breña",
    status: "CERRADO",
    startDate: "2026-03-10",
    endDate: "2026-03-10",
    participants: 6,
    description:
      "Sismo de 4.2 grados generó grietas en paredes de vivienda antigua. Familia de 3 personas con riesgo habitacional.",
    pais: "Perú",
    region: "Lima Metropolitana",
    distrito: "Breña",
    nivelAfectacion: "Moderado",
    numFamiliasAfectadas: 1,
    affectedPeople: [
      {
        id: "p1",
        tipoDoc: "DNI",
        dni: "08765432",
        nombre: "Gladys",
        apellidoPaterno: "Navarro",
        apellidoMaterno: "Pinto",
        edad: "72",
        genero: "Femenino",
        celular: "976432198",
        parentesco: "Propietaria",
      },
    ],
    uploadedFiles: ["informe_sismo_brena.pdf", "acta_donacion_brena.pdf", "acta_cierre_brena.pdf"],
    createdBy: "brigadista",
    createdAt: "2026-03-10T09:00:00.000Z",
    updatedAt: "2026-04-01T11:00:00.000Z",
    updatedBy: "especialistaGRD",
    informeEvaluacion: {
      fecha: "2026-03-14",
      elaboradoPor: "especialistaGRD",
      analisisSituacion:
        "Adulta mayor de 72 años sin red de apoyo familiar. Vivienda con habitabilidad condicionada.",
      nivelUrgencia: "Alta",
      tipoIntervencion: "Donación en especie",
      descripcionAyuda: "Kit de materiales de reforzamiento (malla metálica, cemento, arena).",
      criteriosPriorizacion: [
        "Adultos mayores",
        "Sin redes de apoyo familiar",
        "Pérdida total o parcial de vivienda",
      ],
      recomendacionComite:
        "Se recomienda aprobación. La situación de la adulta mayor sola y sin recursos es de alta vulnerabilidad.",
    },
    informeAtencion: {
      fecha: "2026-03-22",
      elaboradoPor: "especialistaGRD",
      descripcionEntrega: "Entrega de materiales de reforzamiento en domicilio.",
      itemsEntregados: ["20m² de malla metálica", "5 bolsas de cemento", "Arena fina (1/4 m³)"],
      beneficiariosAtendidos: 1,
    },
    history: [
      {
        id: "h1",
        user: "brigadista",
        userRole: "brigadista",
        timestamp: "2026-03-10T09:00:00.000Z",
        action: "creación",
        newStatus: "ABIERTO",
        notes: "Registro — grietas por sismo",
      },
      {
        id: "h2",
        user: "especialistaGRD",
        userRole: "especialistaGRD",
        timestamp: "2026-03-11T10:00:00.000Z",
        action: "asignación",
        prevStatus: "ABIERTO",
        newStatus: "ASIGNADO",
        notes: "Brigadista asignado.",
      },
      {
        id: "h3",
        user: "brigadista",
        userRole: "brigadista",
        timestamp: "2026-03-12T15:00:00.000Z",
        action: "campo",
        prevStatus: "ASIGNADO",
        newStatus: "DATA RECOPILADA",
        notes: "Levantamiento completado.",
      },
      {
        id: "h4",
        user: "especialistaGRD",
        userRole: "especialistaGRD",
        timestamp: "2026-03-14T11:00:00.000Z",
        action: "informe_evaluacion",
        prevStatus: "DATA RECOPILADA",
        newStatus: "EN EVALUACION",
        notes: "Informe elaborado.",
      },
      {
        id: "h5",
        user: "comite",
        userRole: "comite",
        timestamp: "2026-03-16T10:00:00.000Z",
        action: "aprobacion",
        prevStatus: "EN EVALUACION",
        newStatus: "APROBADO",
        notes: "Aprobado. Kit de materiales.",
      },
      {
        id: "h6",
        user: "especialistaGRD",
        userRole: "especialistaGRD",
        timestamp: "2026-03-22T14:00:00.000Z",
        action: "atencion",
        prevStatus: "APROBADO",
        newStatus: "ATENDIDO",
        notes: "Materiales entregados.",
      },
      {
        id: "h7",
        user: "especialistaGRD",
        userRole: "especialistaGRD",
        timestamp: "2026-03-28T11:00:00.000Z",
        action: "seguimiento",
        prevStatus: "ATENDIDO",
        newStatus: "SEGUIMIENTO ABIERTO",
        notes: "Primer seguimiento.",
      },
      {
        id: "h8",
        user: "especialistaGRD",
        userRole: "especialistaGRD",
        timestamp: "2026-04-01T11:00:00.000Z",
        action: "cierre",
        prevStatus: "SEGUIMIENTO ABIERTO",
        newStatus: "CERRADO",
        notes: "Caso cerrado. Vivienda habitable declarada por Defensa Civil.",
      },
    ],
  },
];
